#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      if [[ "$($shome/script/version | jq -r '.lastpass')" != "$LASTPASS_VERSION" ]]; then
        return 1
      fi
      ;;
  esac

  return 0
}

main "$@"
