#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_lastpass="0.0.1"
  jq -n --arg lastpass "$ver_lastpass" '{lastpass: $lastpass}'
}

version "$@"
